/**
 * Reviewed golden Markdown fixture for the canonical research-record memo
 * (schema second-order-research-record-v2) built with ALL THREE tracked
 * contracts unavailable and no export timestamp — the smallest complete
 * build, which still exercises every mandatory section (all 13, with the
 * Mission I ordinary-period comparison ledger between Mission G and
 * Mission J), the full static canonical surface, the explicit unavailable
 * lanes, and the exact ordering and formatting contract.
 *
 * Stored as a lines array joined with "\n" so checkout end-of-line settings
 * can never corrupt the byte-exact comparison.  Every research value below
 * is a literal transcription of the same canonical constants the builder
 * consumes (accepted-corpus, research-findings, effective-independent-
 * evidence, mechanism-family-evidence, representative-case-library); if a
 * canonical snapshot is restated, this golden is restated with it.
 */
const GOLDEN_LINES: ReadonlyArray<string> = [
  "# Second Order — Research Evidence Record",
  "",
  "## 1. Record identity",
  "",
  "- Schema: second-order-research-record-v2",
  "- Evidence Overview route: /evidence",
  "- Research dates and source commits appear within their respective sections below.",
  "- This file is a browser export of the Evidence Overview record; the export itself is not a tracked publication.",
  "",
  "## 2. Purpose and permanent claim ceiling",
  "",
  "This record is a descriptive, event-driven, denominator-aware rendering of the evidence record shown on the Evidence Overview page. It is a portable copy of that record, not a new research publication and not a second interpretation of the research.",
  "",
  "Permanent claim ceiling — this record is:",
  "",
  "- not a recommendation;",
  "- not a prediction surface;",
  "- not evidence of alpha or tradeability;",
  "- not a claim of causality;",
  "- not a claim of single-event statistical significance.",
  "",
  "## 3. Canonical denominator ledger",
  "",
  "Each step is a different denominator answering a different question — not competing estimates of one number. Current accepted-lens snapshot as of 2026-07-11.",
  "",
  "| # | Value | Denominator | Semantic note |",
  "| --- | --- | --- | --- |",
  "| 1 | 180 | archive rows | Full local archive — every saved event, including flagged seeds and staged / pending rows. |",
  "| 2 | 94 | accepted coverage rows | Accepted rows eligible for coverage / event-date reporting. |",
  "| 3 | 86 | accepted track-record rows | Accepted rows used for support / contradiction / unresolved accounting. |",
  "| 4 | 78 / 94 | event-study available | Accepted coverage rows with a SPY-relative event-study readout — a coverage denominator, not a significance claim. |",
  "| 5 | 13 | staged candidates | Outside the accepted and FDR pools; never merged into accepted claims. |",
  "",
  "Staged candidates sit outside the accepted and FDR pools and never enter accepted denominators or claims. Event-study availability is a coverage denominator, not a significance claim; representative cases are illustrative, not evidence.",
  "",
  "## 4. Accepted outcome ledgers",
  "",
  "Two named outcome lenses over the same 86 accepted track-record rows — same denominator, different semantics. Do not merge these two ledgers. No merged, averaged, or composite result exists in this record.",
  "",
  "### Any-support / OR-rule ledger",
  "",
  "- Rule: Any-support OR-rule (db.compute_track_record)",
  "- Denominator: 86 accepted track-record rows",
  "- Split: 59 any-supporting / 14 contradicted / 13 unresolved",
  "- Tie / unresolved handling: no tie rule — a single supporting name is sufficient; rows with no scored directional evidence stay unresolved",
  "- Claim limitation: a descriptive evidence ledger, not predictive validation and not a success rate.",
  "",
  "### Directional-majority ledger",
  "",
  "- Rule: Directional-majority rule (validation_status_v2)",
  "- Denominator: 86 accepted track-record rows — the same rows under a different lens, never merged with the ledger above",
  "- Split: 29 validated / 44 contradicted / 13 unresolved",
  "- Tie / unresolved handling: ties (supports == contradicts) count as contradicted under the frozen current rule",
  "- Claim limitation: the majority labels are the production scorer's vocabulary — evidence sufficiency, not a success verdict and not a claim about future events.",
  "",
  "Why the two distributions differ: One supporting name is enough under the OR-rule, while the directional-majority rule weighs supporting against contradicting names and counts ties as contradicted — that is why the two distributions differ.",
  "",
  "### Baseline characterization — dated snapshot (as of 2026-06-08, superseded denominators)",
  "",
  "The T2/T3/T4 baseline characterization is a frozen snapshot of the then-current market-scored archive (pre-restatement, AP3b-era; the canonical denominators in section 3 supersede its corpus figures). Its findings stay visible:",
  "",
  "- Corpus snapshot: 81 market-scored / 19 any-supporting / 35 contradicted / 27 unresolved; event-study 78 available / 3 unavailable.",
  "- T2A marginal-preserving baseline: observed validated 19; null mean 19.2; 95% interval [13, 26]; verdict not_above_baseline. The raw scored archive is indistinguishable from a marginal-preserving naive baseline.",
  "- T2B primary-only AR-sign (benchmark SPY; 70 eligible observations per horizon): support 1d 0.500 / 5d 0.214 / 20d 0.200; reliability: not reliable — degenerate null. The primary-ticker event-study is degenerate because the eligible primaries are all beneficiaries (predicted-up marginal 1.00), so the permutation null has nothing to shuffle.",
  "- T3A multi-ticker AR-sign (292 eligible ticker observations / 72 eligible events; predicted-up marginal 0.675): 1d support 0.531 vs null mean 0.455, 95% interval [0.401, 0.503]; 5d support 0.339 vs null mean 0.422, 95% interval [0.373, 0.469]; 20d support 0.397 vs null mean 0.399, 95% interval [0.356, 0.438]. Verdict: Mixed — no consistent above-baseline result across horizons. Reliable — exposed-name coverage repaired (V2C); no longer thin. Multi-ticker AR fixes the degeneracy on now-repaired coverage, but still shows no robust above-baseline directional skill: the 1d result does not hold at 5d / 20d.",
  "- T4A exposed-name AR coverage (repaired, V2C): beneficiary 197 / 216 (91.2%); exposed / loser 95 / 113 (84.1%); total 292 / 329 (88.8%). Exposed-name coverage was repaired by an additive price-cache backfill (V2C); the residual gap is delisted / proxy-alias / holiday, not a fixable cache hole.",
  "",
  "## 5. Independence caution",
  "",
  "The 86 accepted track-record rows group into 7 descriptive market-story clusters under transparent same-date / same-primary-ticker-window / duplicate-link rules. The largest cluster holds 79 rows and 12 / 15 representative cases.",
  "",
  "Read the support / contradiction / unresolved counts in section 4 as clustered evidence — a small number of market tapes observed many ways — not 86 separate market stories.",
  "",
  "Descriptive independence-caution only — not an inferential effective sample size, score, rank, p-value, or FDR pool, and not a trading, prediction, or recommendation surface.",
  "",
  "## 6. Mission G — separate historical ledger",
  "",
  "Mission G research record: unavailable",
  "",
  "The /evidence/mission-g contract could not be loaded when this record was exported. No figures are reproduced in its place; the lane is recorded as unavailable rather than omitted. Mission G remains a separate historical ledger and is never pooled with the accepted track record.",
  "",
  "## 7. Mission I — ordinary-period comparison ledger",
  "",
  "Mission I research record: unavailable",
  "",
  "The /evidence/mission-i contract could not be loaded when this record was exported. No figures are reproduced in its place; the lane is recorded as unavailable rather than omitted. Mission I remains a separate ordinary-period comparison ledger and is never pooled with Mission G, Mission J, or the accepted archive.",
  "",
  "## 8. Mission J — separate robustness and transmission ledger",
  "",
  "Mission J research record: unavailable",
  "",
  "The /evidence/mission-j contract could not be loaded when this record was exported. No figures are reproduced in its place; the lane is recorded as unavailable rather than omitted. Mission J remains a separate robustness and transmission ledger and is never pooled with Mission G or the accepted archive.",
  "",
  "## 9. Mechanism-family evidence inventory",
  "",
  "Three family lenses exist on the Evidence Overview; they are different lenses over different denominators, not competing estimates of one count. Families appear in canonical order; no family is ranked.",
  "",
  "### Accepted track-record inventory (E2)",
  "",
  "- Lens: accepted track-record lens (86 rows) grouped by the tested headline overlay",
  "- Buckets: single-match 52 · multi-match 16 · unclassified 18 = 86",
  "",
  "| Family | n | S / C / U | Event-study | Sector hint | Flags |",
  "| --- | --- | --- | --- | --- | --- |",
  "| supply_shock | 20 | 11 / 3 / 6 | 20 / 20 | energy | — |",
  "| geopolitical_conflict_context | 11 | 7 / 2 / 2 | 10 / 11 | energy · industrials | overlay-only |",
  "| tariff | 11 | 5 / 0 / 6 | 8 / 11 | consumer_discretionary · industrials | — |",
  "| sanction | 4 | 0 / 0 / 4 | 1 / 4 | no confident sector match | thin family |",
  "| ceasefire_deescalation | 3 | 2 / 0 / 1 | 2 / 3 | energy | thin family |",
  "| monetary_policy_or_rates | 3 | 1 / 0 / 2 | 2 / 3 | financials | overlay-only · thin family |",
  "",
  "- Illustrative case ids (representative of a family, not evidence for it): supply_shock 29, 38, 210 · geopolitical_conflict_context 7, 30, 232 · tariff 1, 80, 212 · sanction 153, 154, 211 · ceasefire_deescalation 66, 71, 160 · monetary_policy_or_rates 46, 231, 239",
  "- Family-level limitations: the family lens is the tested headline overlay, not the stored mechanism_family taxonomy; overlay-only buckets (geopolitical_conflict_context, monetary_policy_or_rates) sit outside the canonical taxonomy; multi-match (16) and unclassified (18) rows stay visible, not absorbed; staged candidates are excluded from this lens; sectors are descriptive hints only (SPY stays the canonical benchmark); descriptive inventory — no family-level inference, no p-values, no FDR.",
  "",
  "### Deterministic family grouping (T7B-A, dated snapshot as of 2026-06-08)",
  "",
  "- 57 / 81 scored events carry a deterministic family: commodity_squeeze 26 · tariff 13 · sanction 9 · supply_shock 3 · industrial_policy 3 · ceasefire_deescalation 2 · policy_surprise 1 · none / unclassified 24",
  "- Deterministic mechanism-family inference — keyword/asset based, not paid structured extraction.",
  "- This is a family grouping, not a first/second-order channel taxonomy or falsifier layer.",
  "",
  "### Accepted vs staged coverage (as of 2026-06-10)",
  "",
  "- Staged candidates (excluded from every accepted denominator): 13",
  "- Accepted family-labeled rows: tariff 4 · sanction 4 — all curated observations (no thesis outcome)",
  "- Untagged accepted rows: 86 — a data limitation this record states rather than hides",
  "- Staged-only families (zero accepted rows): regulation 5 · labor_inflation 2 · industrial_policy 2",
  "- Tier-1 staged / no-paid shortlist: #303 regulation — DOJ v Apple — conduct antitrust · #304 regulation — DOJ v Google ad-tech — structural antitrust · #313 labor_inflation — UAW strike — production / wage-cost shock",
  "- Staged candidates are not accepted evidence and never enter accepted denominators or claims.",
  "",
  "## 10. Representative-case context",
  "",
  "- 15 illustrative cases across 6 mechanism families: 6 already-covered N1 anchors + 9 newly proposed F1/F2 cases; event-study readout available for 12 / 15; families represented 6 / 6.",
  "- Selection framework: the frozen F1 selection rule (selection frozen @ 399aa8d); outcomes restated 2026-07-11 from the current archive; the selection itself never changes with outcomes. This is a different list from the app Case Library walkthrough, which is a separate editorial slate.",
  "- Why cases are included: walkthrough depth for the family evidence. Cases are illustrative at n = 1 and are not proof; the outcome-frozen selection keeps supportive, contradicted and unresolved cases equally visible.",
  "",
  "| Case | Role | Family | Outcome | Event-study | Caveats |",
  "| --- | --- | --- | --- | --- | --- |",
  "| #1 | anchor | tariff | support | yes | — |",
  "| #46 | anchor | monetary_policy_or_rates | support | yes | overlay-only |",
  "| #61 | anchor | geopolitical_conflict_context | contradiction | yes | overlay-only |",
  "| #66 | anchor | ceasefire_deescalation | support | yes | thin family |",
  "| #210 | anchor | supply_shock | contradiction | yes | outcome restated 2026-07-11 |",
  "| #211 | anchor | sanction | support | yes | thin family · outcome restated 2026-07-11 |",
  "| #7 | new | geopolitical_conflict_context | support | yes | overlay-only |",
  "| #29 | new | supply_shock | contradiction | yes | shared XLE / date cluster |",
  "| #38 | new | supply_shock | support | yes | shared XLE / date cluster |",
  "| #71 | new | ceasefire_deescalation | support | yes | thin family |",
  "| #153 | new | sanction | unresolved | no | thin family · missing readout |",
  "| #154 | new | sanction | unresolved | no | thin family · missing readout |",
  "| #160 | new | ceasefire_deescalation | unresolved | no | thin family · missing readout |",
  "| #212 | new | tariff | support | yes | clean event-date anchor · outcome restated 2026-07-11 |",
  "| #239 | new | monetary_policy_or_rates | support | yes | overlay-only · thin family · outcome restated 2026-07-11 |",
  "",
  "- Readout availability is not the same as thesis support: outcome is thesis-direction scoring of the named tickers, while the event-study readout is the primary ticker vs SPY — a different lens (cases 29 and 38 share a readout but have opposite outcomes).",
  "",
  "## 11. Data limitations and unresolved states",
  "",
  "Stated, not repaired. Only limitations present in the canonical inputs appear here.",
  "",
  "- Event-study coverage: 78 / 94 accepted coverage rows have a SPY-relative event-study readout — a coverage denominator, not a significance claim; the remainder has no computable readout.",
  "- Single-event readout limits (benchmark SPY; horizons 1d / 5d / 20d; estimation window 60 pre-event bars): Single-event rows are n = 1 descriptive readouts of one event window. Not statistical significance: no confidence interval, p-value, or false-discovery (FDR) control at the single-event level. The closed Phase 1 / Phase 2 FDR pools are a separate evidence track with their own frozen q-values.",
  "- Correlated observations: the 86 accepted rows collapse into 7 market-story clusters (section 5); events are date-clustered, not independent.",
  "- Untagged accepted rows: 86 accepted rows carry no mechanism_family label (section 8).",
  "- Unresolved outcomes stay visible: 13 unresolved under the any-support lens and 13 under the directional-majority lens (section 4); representative cases 153, 154, 160 have missing readouts (section 9).",
  "- Coverage repair residue (V2C executed): live exposed / loser AR coverage 95 / 113 and total 292 / 329 after promoting 8,538 additive price-cache rows into live; residual missing units 37 (26 distinct symbols, 28 windows) — gap_fill_maybe 18 (fixable) · no_cache_backfill 10 (fixable) · alias_manual_review 6 (not fixable) · future_not_yet 2 (not fixable) · delisted_stale 1 (not fixable).",
  "- Executed via the V2C operator-approved promotion: +8,538 additive price-cache rows copied into live; only price_cache changed (events and other tables unchanged).",
  "- Daily-close provider only; no existing live row was overwritten (48 existing-key value differences were kept as-is).",
  "- Residual missingness is delisted / proxy-alias / residual gaps — not a simple backfill.",
  "- Coverage-repair boundary: The repair improves coverage / representativeness only. It does not create statistical significance, an edge, or a directional claim; a single-event AR stays an n = 1 descriptive point estimate. The temporal-clustering ceiling — the corpus is ~90% one 2-month window — is NOT lifted by coverage repair.",
  "- Missing provenance: fields not canonically recorded are marked \"not recorded\" in section 12.",
  "- Mission G research record: unavailable — its limitation and falsifier detail could not be exported (section 6).",
  "- Mission I research record: unavailable — its structural-unavailability and fragility detail could not be exported (section 7).",
  "- Mission J research record: unavailable — its measurement-limited and unresolved detail could not be exported (section 8).",
  "",
  "## 12. Provenance and reproduction appendix",
  "",
  "Reproduction commands are recorded for reference only; nothing in this export executes them. Fields not canonically recorded say \"not recorded\".",
  "",
  "### Canonical denominators and accepted outcome ledgers",
  "",
  "- Source document: not recorded (dated snapshot restated read-only from the live archive)",
  "- Source commit: not recorded",
  "- Restatement date: 2026-07-11",
  "- Reproduction (any-support OR-rule ledger): `python -c \"import db; db.init_db(); print(db.compute_track_record())\"`",
  "- Reproduction (directional-majority ledger): `python scripts/validation_status_calibration_report.py --db-path events.db`",
  "",
  "### Baseline characterization (T2/T3/T4)",
  "",
  "- Source document: not recorded",
  "- Source commit: not recorded",
  "- Snapshot date: 2026-06-08",
  "- Reproduction command: not recorded",
  "",
  "### Effective independent evidence (K2)",
  "",
  "- Source document: stats/EFFECTIVE_INDEPENDENT_EVIDENCE.md",
  "- Source commit: 8d247ea",
  "- Reproduction: `python scripts/effective_independent_evidence_report.py --db-path events.db --json`",
  "",
  "### Mechanism-family evidence inventory (E1)",
  "",
  "- Source document: stats/MECHANISM_FAMILY_EVIDENCE_INVENTORY.md",
  "- Source commit: 77354e9",
  "- Reproduction: `python scripts/mechanism_family_evidence_inventory.py --db-path events.db --json`",
  "",
  "### Mechanism-family coverage (AZ1)",
  "",
  "- Source documents: stats/MECHANISM_FAMILY_OVERVIEW.md · stats/STAGED_CANDIDATE_SHORTLIST.md",
  "- Source commit: not recorded",
  "- As-of date: 2026-06-10",
  "- Reproduction: `python scripts/mechanism_family_overview_report.py --db-path events.db --json`",
  "",
  "### Representative research set (F1/F2)",
  "",
  "- Source documents: stats/REPRESENTATIVE_CASE_EXPANSION.md · stats/EXPANDED_CASE_NOTES.md",
  "- Source commit: 399aa8d",
  "- Outcomes restated: 2026-07-11",
  "- Reproduction command: not recorded",
  "",
  "### Mission G historical record",
  "",
  "- Mission G research record: unavailable — no provenance could be exported.",
  "",
  "### Mission I published record",
  "",
  "- Mission I research record: unavailable — no provenance could be exported.",
  "",
  "### Mission J published record",
  "",
  "- Mission J research record: unavailable — no provenance could be exported.",
  "",
  "## 13. Final non-claims",
  "",
  "Standing non-claims of the evidence record:",
  "",
  "- Descriptive archive characterization only.",
  "- Not a trading or prediction surface, and not a recommendation.",
  "- Not a measure of edge.",
  "- Not a statistical-significance test; the events are not independent.",
  "- Single-event AR signs are n = 1 point estimates.",
  "- Events are date-clustered / not independent.",
  "- Separate from the closed Phase 1 / Phase 2 FDR pools; no pool q-values are used or implied.",
  "",
  "This record does not establish causality, statistical significance,",
  "predictive performance, alpha, tradeability, or an investment recommendation.",
];

export const GOLDEN_RESEARCH_RECORD_ALL_UNAVAILABLE: string =
  GOLDEN_LINES.join("\n") + "\n";
